apiVersion: v1
kind: Secret
metadata:
  name: gimbr-secrets
type: Opaque
data:
  secret: eW91cl9naW1icl9zZWNyZXQ=       # base64 encoded value of YOUR_SECRET
  sentry_dsn: eW91cl9zZW50cnlfZHNuaGVyZQ==  # base64 encoded value of YOUR_SENTRY_DSN