core:
  executor: LocalExecutor
  dags_folder: ${AIRFLOW_HOME}/dags
  base_log_folder: ${AIRFLOW_HOME}/logs
  load_examples: False
  sql_alchemy_conn: sqlite:///airflow.db

logging:
  logging_level: INFO
  remote_logging: False

smtp:
  smtp_host: smtp.gmail.com
  smtp_starttls: True
  smtp_ssl: False
  smtp_user: your-email@example.com
  smtp_password: ${SMTP_PASSWORD}
  smtp_port: 587
  smtp_mail_from: your-email@example.com