version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - prometheus

  mlflow:
    image: mlflow/mlflow:2.11.3
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=s3://mybucket/mlflow-artifacts

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus_config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  dvc:
    image: iterative/dvc:3.53.1
    volumes:
      - .:/workspace
    working_dir: /workspace

  airflow:
    image: apache/airflow:2.9.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:///airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./configs/airflow_config.yaml:/opt/airflow/airflow.cfg
      - ./dags:/opt/airflow/dags

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data

volumes:
  minio_data: